---
language: php 

script:
  - phpunit
  - mkdir logs
  - phpunit --coverage-clover logs/clover.xml
  - php vendor/bin/security-checker security:check composer.lock

after_script:
  - php vendor/bin/coveralls -v

before_install:
  - composer self-update

install:
  - composer install

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
